yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/add_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
</footer> 

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item"> 
              <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="">Изменить пароль</a>
              <!-- Ссылка пока не существует -->
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              Пользователь: {{ user.username }}
            </li>
          {% else %}
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %} 
      </ul>
    </div>
  </nav>      
</header> 

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}