yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Группы'
        verbose_name = 'Группа'


class Post(models.Model):
    text = models.TextField(verbose_name='Текст')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name_plural = 'Посты'
        verbose_name = 'Пост'


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'

yatube/posts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': _('Текст'),
            'group': _('Группа'),
            'image': _('Изображение')
        }
        help_texts = {
            'text': _('Пишите сюда текст поста'),
            'group': _('Группа, которой будет принадлежать пост'),
            'image': _('Изображение к посту')
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': _('Текст комментария'),
        }
        help_text = {
            'text': _('Пишите сюда текст комментария')
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

from .models import Post, Group, Follow
from .forms import PostForm, CommentForm

POSTS_PER_PAGE = 10

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.select_related('author', 'group').all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    post_list = group.posts.select_related('author', 'group').all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts_number = user.posts.count()
    user_posts = user.posts.select_related('author', 'group').all()
    paginator = Paginator(user_posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        following = user.following.filter(user=request.user).exists()
    context = {
        'username': user,
        'posts_number': posts_number,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'count_posts': post.author.posts.count(),
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {
        'form': form,
        'is_edit': False
    }
    return render(request, 'posts/create_post.html', context)


def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None,
                    instance=post,
                    files=request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form, 'post': post, 'is_edit': True}
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    user_followings = Follow.objects.filter(user=user)
    if author != user and not user_followings.filter(author=author).exists():
        Follow.objects.create(
            user=user,
            author=author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}
Новый пост
{% endblock %}
{% block content %}   
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Новый пост
          {% endif %}  
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post" enctype="multipart/form-data"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Последние обновления избранных авторов
{% endblock %}
{% block content %}
  <div class="container py-5">
    <title>Последние обновления избранных авторов</title>
    {% include 'includes/switcher.html' %}
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}"> все посты пользователя </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>      
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
      </article>
      {% if post.group %}<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{{ group.title }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}"> все посты пользователя </a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
      </article>
      {% if post.group %}<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
  <div class="container py-5">
    <title>Последние обновления на сайте</title>
    {% include 'includes/switcher.html' %}
    {% cache 20 index_page page_obj %}
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }} <a href="{% url 'posts:profile' post.author.username %}"> все посты пользователя </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>      
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
        </article>
        {% if post.group %}<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% endcache %}
  {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>               
          {% if post.group %}  
            <li class="list-group-item">
              Группа: {{ post.group }}
              {% if post.group %}<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
            </li>
          {% endif %}           
          <li class="list-group-item">
            Автор: {{post.author.get_full_name}} {{post.author.username}}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span>{{ count_posts }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      </article>
      {% include 'includes/add_comment.html' %}
    </div>     
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Профайл пользователя {{username.first_name}} {{username.last_name}}
{% endblock %}
{% block content %}
<div class="container py-5">      
    <div class="mb-5">
        <h1>Все посты пользователя {{username.first_name}} {{username.last_name}} </h1>  
        <h3>Всего постов: {{ posts_number }} </h3>
        {% if request.user != username %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' username.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' username.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}
    </div>
    {% for post in page_obj %} 
        <article>
        <ul>
            <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
            {{ post.text }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
        </article>
        {% if post.group %}<a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>{% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
</div>
{% endblock %}