yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/models.py
# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
            {% csrf_token %}

            {% for field in form %}
              <div class="form-group row my-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                <div>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
  </div> 
{% endblock %} 